### ISSUE TITLE
[8.0.1] Killing Blow on all mob kills

### ISSUE THREAD

**Issue by Beet4** [Choonster-WoW-AddOns/KillingBlow_Enhanced#1]
Since the last update for patch 8.0.1 I get killing blows for every mob that I kill, not only players. This occured outside in the world when I tested, might do so in more places as well. Has not been tested.

**Comment by designerwood** [comment]
This also happened to me on a training dummy. I cast moonfire and it spammed Killing Blow every moonfire tick. Would be nice to be able to toggle it for only arena/bg's. Fun addon though. 👍

**Comment by Choonster** [comment]
As far as I can tell, the AddOn has always recorded mob kills outside of PvP zones; this hasn't changed in the 8.0.1 update. You can set `PVP_ONLY` to `true` at the top of __core.lua__ to disable the recording of killing blows outside of PvP zones.

**Comment by Beet4** [comment]
Never had this before, I guess the default value has changed then?

**Comment by Choonster** [comment]
Yes, it looks like I set `PVP_ONLY` to `false` so I could test it outside of PvP and then accidentally committed that change in the 8.0.1 update.

I'll change it back tonight and release a new version.

**Comment by Choonster** [comment]
This has been fixed in version 1.20.
